service: todo-list-api

provider:
  name: aws
  runtime: python3.9
  environment:
    DYNAMODB_TABLE: ${self:service}-table

functions:
  createTodo:
    handler: src/handler.create_todo
    events:
      - http:
          path: todos
          method: post
  getTodo:
    handler: src/handler.get_todo
    events:
      - http:
          path: todos/{id}
          method: get
  updateTodo:
    handler: src/handler.update_todo
    events:
      - http:
          path: todos/{id}
          method: put
  deleteTodo:
    handler: src/handler.delete_todo
    events:
      - http:
          path: todos/{id}
          method: delete

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
